### ISSUE TITLE
Is there a way to count blinks? 

### ISSUE THREAD

**Issue by jaydeepc** [crystoll/projectillithid#1]
Hi @crystoll ,

Great intiative and work on the library. I was working on creating a similar one, but glad to see its done.
Quick question, in mindwave.py, i see the attribute "blinks", but when I try to print it, it always says "0".

Am I missing something?

**Comment by crystoll** [comment]
Hi, glad to hear this is useful for you. You are not missing anything, that's how it should be working. Now that being said, I have never actually tested blinks functionality, so it ia possiböe there is a bug. Or hardware differences might cauae issues.

I'm currently on vacation and no access to hardware, but I could try to confirm the bug by testing on my hardware, at some point.

Another possibility: this is a fork of other mindwave libraries, so one could perhaps take a look if original libraries habe any differences in the blink code.

I know it can be made to work, quite reliably, since I also tested the blink long ago, before my library version.
